django_blog_project/app_blog/urls.py
from django.urls import path
from . import views  # or from app_blog import views

app_name = 'app_blog'


urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

django_blog_project/app_login/urls.py
from django.urls import path
from app_login import views

app_name = 'app_login'

urlpatterns = [
    path("signup/", views.sign_up, name="signup"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("change-profile/", views.user_change, name="user_change"),
    path("password/", views.pass_change, name="pass_change"),
    path("add_picture/", views.add_pro_pic, name="add_pro_pic"),
    path("change_picture/", views.change_pro_pic, name="change_pro_pic"),
]

django_blog_project/django_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


# for image handling
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.index, name='index'),
]


# for image handling
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog_project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title_block %} {% endblock %}</title>
    <!-- css file for bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- js file for bootstarp -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
    <!-- icons from fontawesome -->
    <script src="https://kit.fontawesome.com/a2128510fa.js" crossorigin="anonymous"></script>
</head>


<body>

    <!-- this is navbar section -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Django Blog Project</a>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item active">
                <a class="nav-link" aria-current="page" href="{% url 'index' %}"><img src="/media/logo-home.jpg" width="40px"></a>
              </li>
            {% if user.is_authenticated %}
              {% comment %} <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'app_login:profile' %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'app_login:logout' %}">Logout</a>
              </li> {% endcomment %}

              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      @{{ user.username}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'app_blog:my_blogs' %}">My Blogs</a></li>
                      <li><a class="dropdown-item" href="{% url 'app_blog:create_blog' %}">Write Blog</a></li>
                      <li><a class="dropdown-item" href="{% url 'app_login:profile' %}">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'app_login:logout' %}">Logout</a></li>
                      {% comment %} <li><a class="dropdown-item" href="#">Something else here</a></li> {% endcomment %}
                    </ul>
                  </li>
                </ul>
              </div>


            {% else %}
              
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'app_login:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'app_login:login' %}">Login</a>
              </li>
            {% endif %}
            </ul>
          </div>
        </div>
    </nav>

<div class="container" style="padding-top: 20px">
  {% block body_block %}

  {% endblock %}
</div>

</body>
</html>