django_blog_project/app_blog/urls.py
from django.urls import path
from . import views  # or from app_blog import views

app_name = 'app_blog'


urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

django_blog_project/app_login/urls.py
from django.urls import path
from app_login import views

app_name = 'app_login'

urlpatterns = [
    path("signup/", views.sign_up, name="signup"),
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("change-profile/", views.user_change, name="user_change"),
    path("password/", views.pass_change, name="pass_change"),
    path("add_picture/", views.add_pro_pic, name="add_pro_pic"),
    path("change_picture/", views.change_pro_pic, name="change_pro_pic"),
]

django_blog_project/django_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


# for image handling
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.index, name='index'),
]


# for image handling
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog_project/app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

django_blog_project/app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.urls import reverse
from app_login.models import UserProfile
from django.forms import ModelForm


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email", required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].help_text = (
            "Raw passwords are not stored, so there is no way to see this user’s password, but you can change the password using <a href='{}'>this form</a>."
        ).format(reverse("app_login:pass_change"))


class ProfilePic(ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'
        #fields = ['profile_pic', ]
        exclude = ['user', ]

django_blog_project/app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, UserProfileChange, ProfilePic

# Create your views here.

def sign_up(request):
    #form = UserCreationForm()
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        #form = UserCreationForm(request.POST)
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {'form': form, 'registered': registered}
    return render(request, 'app_login/signup.html', context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                print('login successful')
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'app_login/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):
    return render(request, 'app_login/profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserCreationForm(instance=current_user)
    return render(request, 'app_login/change_profile.html', context={'form':form})

# @login_required
# def pass_change(request):
#     current_user = request.user
#     changed = False
#     form = PasswordChangeForm(current_user)
#     if request.method == 'POST':
#         form = PasswordChangeForm(current_user, request.POST)
#         if form.is_valid():
#             form.save()
#             changed = True
#     return render(request, 'app_login/pass_change.html', context={'form':form, 'changed':changed})


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    #form = PasswordChangeForm(user=current_user)  # works same as above
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, request.POST)
        #form = PasswordChangeForm(user=current_user, data=request.POST)  # works same as above
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'app_login/pass_change.html', context={'form':form, 'changed':changed})
        

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/add_pro_pic.html', context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/add_pro_pic.html', context={'form':form})
                  
    
                  
                  





django_blog_project/templates/app_login/add_pro_pic.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} Login {% endblock %}

{% block body_block %}
<h2>Login:</h2>
<form method="POST" enctype="multipart/form-data">
{{ form|crispy }}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Add</button>
</form>
{% endblock %}

django_blog_project/templates/app_login/change_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} Change Profile {% endblock %}

{% block body_block %}

<form method="POST">
{{ form|crispy }}
{% csrf_token %}
<button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>


{% endblock %}

django_blog_project/templates/app_login/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} Login {% endblock %}

{% block body_block %}
<h2>Login:</h2>
<form method="POST">
{{ form|crispy }}
{% csrf_token %}
<button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>
{% endblock %}

django_blog_project/templates/app_login/pass_change.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} Change Password {% endblock %}

{% block body_block %}
{% if changed %}
<div class="alert alert-success">
    Password changed Succcessfully
</div>
{% endif %}

<form method="POST">
{{ form|crispy }}
{% csrf_token %}
<button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>


{% endblock %}

django_blog_project/templates/app_login/profile.html
{% extends "base.html" %}

{% block title_block %} Your Profile {% endblock %}

{% block body_block %}
<h2>Your Profile</h2>

{% if user.user_profile %}
    <img src='/media/{{ user.user_profile.profile_pic }}' class='img-thumbnail' width='150px'>
    <br>
    <br>
    <a href="{% url 'app_login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
{% else %}
    <img src='/media/profile_pics/avatar-male.jpg' class='img-thumbnail' width='150px'>
    <br>
    <br>
    <a href="{% url 'app_login:add_pro_pic' %}" class="btn btn-info btn-sm">Add Profile Pic</a>
{% endif %}

<br><br>

<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }}</p>
<br>
<a href={% url 'app_login:user_change' %} class="btn btn-warning btn-sm">Change Profile Info</a>
{% endblock %}

django_blog_project/templates/app_login/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} Create New Account {% endblock %}

{% block body_block %}

{% if registered %}
<div class="alert alert-success">Account Created Successfully!  <a href="{% url 'app_login:login' %}">Login Here</a></div>
{% else %}

<h3>Create New Account</h3>
<form method="POST">
{{ form|crispy }}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already have an Account? <a href="{% url 'app_login:login' %}">Login Here</a>
{% endif %}

{% endblock %}