django_blog_project/app_blog/urls.py
from django.urls import path
from . import views  # or from app_blog import views

app_name = 'app_blog'


urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

django_blog_project/django_blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


# for image handling
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('app_login.urls')),
    path('blog/', include('app_blog.urls')),
    path('', views.index, name='index'),
]


# for image handling
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog_project/app_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name='Put a Title')
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']        # both tuple and list is accepted as ordering

    def __str__(self):
        return self.comment
    
class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

    def __str__(self):
        return self.user + " likes " + self.blog

django_blog_project/app_blog/forms.py
from django import forms
from app_blog.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

django_blog_project/app_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView, View, TemplateView 
from app_blog.models import Blog, Comment, Like
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from app_blog.forms import CommentForm


# Create your views here.

# def blog_list(request):
#     return render(request, 'app_blog/blog_list.html', context={})


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'app_blog/create_blog.html'
    fields = ['blog_title', 'blog_content', 'blog_image']

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" " , "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))
    

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/blog_list.html'
    #queryset = Blog.objects.order_by('-publish_date')


@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)

    already_liked = Like.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    comment_form = CommentForm()
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':slug}))

    return render(request, 'app_blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked })


@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Like(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':blog.slug}))


login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':blog.slug}))


class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'app_blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'app_blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('app_blog:blog_details', kwargs={'slug':self.object.slug})

django_blog_project/templates/app_blog/blog_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} {{ blog.blog_title }} {% endblock %}

{% block body_block %}

<div class="row">
    <div class="col-sm-6">
        <h2>{{ blog.blog_title }}</h2>
        <h4>Posted By: @{{ blog.author }}</h4>
        <i><h6>Published On: {{ blog.publish_date }}</h6></i>
        <i><h6>Updated On: {{ blog.update_date }}</h6></i>
        <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
    </div>
    <div class="col-sm-6">
        <img src="/media/{{ blog.blog_image }}" width="50%">
    </div>
    <p>{{ blog.blog_content|linebreaks }}</p>
</div>

{% if not liked %}
<a href="{% url 'app_blog:liked_post' pk=blog.pk %}">
    <i class="fa-solid fa-thumbs-up fa-2xl"></i>
</a>
{% else %}
<a href="{% url 'app_blog:unliked_post' pk=blog.pk %}">
    <i class="fa-solid fa-thumbs-down fa-2xl"></i>
</a>
{% endif %}



<div class="row">
    <div class="col-sm-6">
        <hr>
        <h5>Comments: </h5>
        {% for comment in blog.blog_comment.all %}
        <p>
            <a href="#">@{{ comment.user }}</a>
            <br>
            {{ comment.comment }}
            <br>
            <h6><i>{{ comment.comment_date }}</i></h6>
        </p>
        {% endfor %}
    </div>
    <div class="col-sm-6">
        <form method="POST">
            {{ comment_form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Comment</button>
        </form>
    </div>
</div>

{% endblock %}

django_blog_project/templates/app_blog/blog_list.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title_block %} Home - Blog List {% endblock %}

{% block body_block %}

{% for blog in blogs %}
<h3>{{ blog.blog_title }}</h3>
<h6><i>{{ blog.publish_date }}</i></h6>
<div class=row>
    <div class=col-sm-4>
        <img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="50%">
    </div>
    <div class=col-sm-8>
        <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a></p>
        <h6>Posted By: <a href="#">{{ blog.author }}</a></h6>
        <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
    </div>
</div>

{% endfor %}



{% endblock %}

django_blog_project/templates/app_blog/create_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} Write Blog {% endblock %}

{% block body_block %}
<h3>Start writing a blog</h3>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>


{% endblock %}

django_blog_project/templates/app_blog/edit_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title_block %} {{ blog.blog_title }} {% endblock %}

{% block body_block %}
{% if blog.author == user %}
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-sm">Update</button>
    </form>
{% else %}
<div class="alert alert-danger">You are not allowed to view this page.</div>
{% endif %}


{% endblock %}

django_blog_project/templates/app_blog/my_blogs.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title_block %} Blogs of {{ user }} {% endblock %}

{% block body_block %}

{% for blog in user.post_author.all %}
<h3>{{ blog.blog_title }}</h3>
<h6><i>Created: {{ blog.publish_date }}</i></h6>
<h6><i>Updated: {{ blog.update_date }}</i></h6>
<div class=row>
    <div class=col-sm-4>
        <img src="/media/{{ blog.blog_image }}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="50%">
    </div>
    <div class=col-sm-8>
        <p>{{ blog.blog_content|range_filter|linebreaks }} <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a></p>
        <h6>Posted By: <a href="#">{{ blog.author }}</a></h6>
        <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
        <a href="{% url 'app_blog:edit_blog' pk=blog.pk %}" class="btn btn-success btn-sm">Edit</a>
    </div>
    
</div>

<hr>

{% endfor %}



{% endblock %}